# Generated by Django 6.0.3 on 2026-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50, verbose_name='nom_complet')),
                ('specialites', models.CharField(max_length=50, verbose_name='specialites')),
                ('description', models.TextField(verbose_name='description ')),
                ('adresse', models.CharField(max_length=50, verbose_name='adresse')),
                ('est_actif', models.BooleanField(blank=True, default=True, null=True, verbose_name='est_actif')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='date_creation')),
                ('telephone', models.CharField(max_length=50, verbose_name='telephone')),
                ('image', models.URLField(blank=True, null=True, verbose_name='image')),
            ],
        ),
    ]
